version: "3.7"

services:
  app:
    build: ./
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://user:password@mysql/dbname
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbname

volumes:
  todo-mysql-data:
